export const InitalState = {
    divTipoPersona: '',
    arrayTipoPersonaSelect: null,
    divTipoPersonaError: '',
    divTiempo:'',
    arrayTiempoSelect: null,
    divTiempoError:'',
    divMontoMinimoComision:'',
    montoMinimoComision:'0.00',
    divMontoMinimoComisionError:'',
    divMontoComision:'',
    montoComision:'0.00',
    divMontoComisionError:'',
    divModoPago:'',
    arrayModoPagoSelect: null,
    divModoPagoError:'',
    divEspecifique:'',
    especifique:'',
    divEspecifiqueError:'',
    divPorcentajeComision:'',
    porcentajeComision:'',
    divPorcentajeComisionError:'',
    action:0,
    hideEspecifique:'hide',    
    hideMontoComision:'hide',    
    hidePorcentajeComision:'hide',    
    hideModoPago:'hide',    
    collapse: false,
    loading:'show', 
}