export const InitalState = {
    activeTab: "1",
    divTipoPersona: '',
    arrayTipoPersonaSelect: null,
    divTipoPersonaError: '',
    divTiempo:'',
    tiempoDias: 0,
    divTiempoError:'',
    divTipo:'',
    arrayTipo:null,
    divTipoError:'',
    divMontoMinimoComision:'',
    montoMinimoComision:'0.00',
    divMontoMinimoComisionError:'',
    divNroPersonasReferenciadas:'',
    nroPersonasReferenciadas:'0',
    divNroPersonasReferenciadasError:'',
    divPersonalExterno:'',
    arrayPersonalExterno:null,
    divPersonalExternoError:'',
    divMontoComision:'',
    montoComision:'0.00',
    divMontoComisionError:'',    
    divModoPago:'',
    arrayModoPagoSelect: null,
    divModoPagoError:'',
    divEspecifique:'',
    especifique:'',
    divEspecifiqueError:'',
    divPorcentajeComision:'',
    porcentajeComision:'',
    divPorcentajeComisionError:'',
    action:0,
    hideEspecifique:'hide',    
    hideMontoComision:'hide',    
    hidePorcentajeComision:'hide',    
    hideModoPago:'hide',    
    hideTipoNroPersonas:'hide',
    hideTipoMontoMinimo:'hide',
    hidePersonalExterno:'hide',
    collapse: false,
    loading:'show', 
}