const selectExento = 
[
  { value: 'NO', label: 'NO' },
  { value: 'SI', label: 'SI' },

];  

export const InitalState = {
    activeTab: "1",
    productoId: '0',
    loteId: '0',
    keyProduct: '',
    nroLote: '0',
    divTipoCompra: '',
    arrayTipoCompraSelect: null,
    divTipoCompraError: '',
    divProveedor: '',
    arrayProveedorSelect: null,
    divProveedorError: '',
    divNroCompra: '',
    nroCompra: '',
    divNroCompraError: '',
    divNroControl: '',
    nroControl: '',
    divNroControlError: '',
    divObservacion: '',
    observacion: '',
    divObservacionError: '',
    divCompraDate: '',
    compraDate: new Date(),
    divCompraDateError: '',
    divProducto: '',
    producto: '',
    divProductoError: '',
    divTipo: '',
    arrayTipoSelect: null,
    divTipoError: '',
    divCodigo: '',
    codigo: '',
    divCodigoError: '',
    divCantidad: '',
    cantidad: '0',
    divCantidadError: '',
    divNuevaCantidad: '',
    nuevaCantidad: '0',
    divNuevaCantidadError: '',    
    divCantidadAvailable: '',
    cantidadAvailable: '0',
    divCantidadAvailableError: '',
    divPrecio: '',
    precio: '0.00',
    divPrecioError: '',
    divPrecioVenta: '',
    precioVenta: '0.00',
    divPrecioVentaError: '',
    divDescuento: '',
    descuento: '0',
    divDescuentoError: '',
    divLimiteStock: '',
    limiteStock: '0',
    divLimiteStockError: '',
    divDescripcion: '',
    descripcion: '',
    divDescripcionError: '',
    fotoInvalid: false,
    fotoError: '',            
    foto: null,
    divExento:'',
    arrayExentoSelect: null,
    arrayExento: selectExento,
    divExentoError: '',
    divDireccionPartida:'',
    direccionPartida:'',
    divDireccionPartidaError:'',
    divDireccionLlegada:'',
    direccionLlegada:'',
    divDireccionLlegadaError:'',
    divBuscarProducto: '',
    arrayBuscarProductoSelect: null,
    divBuscarProductoError: '', 
    divTableProductos: '',
    divSucursalesSelect: '',
    arraySucursalesSelect: null,
    divSucursalesSelectError: '',
    subTotal: 0.00,
    impuesto: 0.00,
    total: 0.00,
    acumSubTotal: 0.00,
    acumImp: 0.00,
    acumTotal: 0.00,
    disabled: false,    
    popoverOpen: false,
    collapse: false,
    modal:false,
    modalHeader: '',
    modalFooter: '',
    showHide: '',
    showHideEditar: '',    
    cantidadRestante: '0',
    divMotivoSalida: '',
    arrayMotivoSalidaSelect: null,
    divMotivoSalidaError: '',
    divEspecifique: '',
    especifique: '',
    divEspecifiqueError: '',
    disabledEspecifique: true,
    divTipoTransfer: '',
    arrayTipoTransfer: null,
    divTipoTransferError: '',
    divOptionOne: '',
    arrayOptionOne: null,
    arraySelectOptionOne: [],
    divOptionOneError: '',
    divOptionTwo: '',
    arrayOptionTwo: null,
    arraySelectOptionTwo: [],
    divOptionTwoError: '',    
    checked: false,
    option:0,
    arrayOptionsShelfs: [],
    divAviso:'',
    divAlmacen:'',
    arrayAlmacen: null,
    divAlmacenError: '',
    divEstante:'',
    arrayEstante: null,
    arrayEstanteSelect: [],
    divEstanteError: '',
    sucursal_central_token: '',
    divQuantityRegister:'',
    quantityRegister:'',
    divQuantityRegisterError:'',
    divOrdenTransfer:'',
    arrayOrdenTransfer:null,
    divOrdenTransferError:'',
    divOrigenOrden:'',
    arrayOrigenOrden:null,
    divOrigenOrdenError:'',
    divDestinoOrden:'',
    arrayDestinoOrden:null,
    divDestinoOrdenError:'',
    loading:'show',       
}