export const InitalState = {
    almacen: '',
    almacenError: '',
    almacenInvalid: '',
    arraySucursalesSelect: null,
    divSucursalesSelect: '',
    divSucursalesSelectError: '',                               
    descripcion: '',
    descripcionError: '',
    descripcionInvalid: false,
    estante: '',
    estanteError: '',
    estanteInvalid: '',
    estanteDescripcion: '',
    estanteDescripcionError: '',
    estanteDescripcionInvalid: false,
    action:0,
    collapse: false,
    loading:'show', 
}